# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a016312fd052294f8843dea2192690e0060a881a587a0ea779015e7f80a9ce6633a26140f1b9543c0407d18ec4c20fc684eec53c749196da194113028266dd75

test:
  secret_key_base: 35f3d701d5619a4979ad4e1f8591605b110bf27c5458a0218716c656ba6f64b78b31ccfb3546145b10746b5e154042cd3a9ae04ea7ed7f43859ab655582482b8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
